fix : updated inputs
iprankurpandey/demo-agro pull request #10
Opened 2022-02-09 10:22 UTC by iprankurpandey

2022-02-09 11:50 UTC, Naman-Saxena1 commented
Looks fine.

2022-02-09 12:24 UTC, rahulk31 commented
Looks good, can be merged.

2022-02-19 03:28 UTC, varun1233 approved these changes
Code looks good

2022-02-19 05:45 UTC, sri-rishi requested changes

2022-02-19 05:45 UTC, sri-rishi commented on components/Input/input.css
> +    /* content: '✖'; */
remove comments

2022-02-19 11:12 UTC, merged